version: '3'

services: 
  app:
    build: 
      context: node
      #dockerfile: Dockerfile
    container_name: app-node
    hostname: app-node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    networks: 
      - challenge-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    restart: unless-stopped
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=xupacabra
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - challenge-network

  webserver:
    build: 
      context: nginx
      #dockerfile: Dockerfile
    container_name: webserver-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - challenge-network

networks: 
  challenge-network:
    driver: bridge 
