version: '3'

services: 
  app:
    build: 
      context: node
      dockerfile: Dockerfile.prod
    container_name: challenge-app
    hostname: challenge-app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    entrypoint: node index.js
    volumes: 
      - ./node:/home/node/app
      - ./node/node_modules:/home/node/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    networks: 
      - challenge-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: challenge-db
    restart: unless-stopped
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=xupacabra
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - challenge-network

  webserver:
    build: 
      context: nginx
      #dockerfile: Dockerfile
    container_name: challenge-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - challenge-network

networks: 
  challenge-network:
    driver: bridge 
 